name: tests

on:
  pull_request:

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutÂ·
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.5"

      - name: Test code
        id: test-code
        run: |
          go build ./...
          go test -race ./...
